# Generated by Django 5.2.16 on 2026-08-02 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Марка')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Марка авто',
                'verbose_name_plural': 'Марки авто',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель')),
                ('slug', models.SlugField(max_length=120, verbose_name='Slug')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='catalog.carmake', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Модель авто',
                'verbose_name_plural': 'Модели авто',
                'ordering': ['make__name', 'name'],
                'unique_together': {('make', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('sku_normalized', models.CharField(blank=True, db_index=True, editable=False, max_length=100, verbose_name='Артикул (нормализованный)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Наименование (рус)')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Наименование (англ)')),
                ('condition', models.CharField(choices=[('new', 'Новый'), ('used', 'Б/У')], default='new', max_length=10, verbose_name='Состояние')),
                ('price_rub', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена продажи, ₽')),
                ('price_krw', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Цена продажи, ₩')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (рус)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Изображение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCrossNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Кросс-номер')),
                ('number_normalized', models.CharField(blank=True, db_index=True, editable=False, max_length=100, verbose_name='Нормализованный')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Комментарий')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_numbers', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Кросс-номер',
                'verbose_name_plural': 'Кросс-номера',
                'unique_together': {('product', 'number_normalized')},
            },
        ),
        migrations.CreateModel(
            name='ProductVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год с')),
                ('year_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год по')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.carmake', verbose_name='Марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.carmodel', verbose_name='Модель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Применимость',
                'verbose_name_plural': 'Применимость',
                'unique_together': {('product', 'make', 'model', 'year_from', 'year_to')},
            },
        ),
    ]
